flowchart TB
    constant_0{{"constant_0<br>[], id=0, ty=4<br>/norm_k/Constant_1_output_0_QuantizeLinear_Output"}}
    classDef constant fill:#90ee90,stroke:#006400,stroke-width:2px;;
    class constant_0 constant;
    constant_1{{"constant_1<br>[], id=1, ty=1<br>/norm_k/Constant_1_output_0_scale"}}
    class constant_1 constant;
    constant_2{{"constant_2<br>[], id=2, ty=4<br>/norm_k/Constant_1_output_0_zero_point"}}
    class constant_2 constant;
    com_microsoft_DequantizeLinear_0["com_microsoft_DequantizeLinear_0<br>[], id=3, ty=1<br>/norm_k/Constant_1_output_0_DequantizeLinear_Output"]
    constant_0 -.-> com_microsoft_DequantizeLinear_0
    constant_1 -.-> com_microsoft_DequantizeLinear_0
    constant_2 -.-> com_microsoft_DequantizeLinear_0
    classDef com_microsoft_DequantizeLinear fill:#ffffe0,stroke:#ff8c00,stroke-width:2px;;
    class com_microsoft_DequantizeLinear_0 com_microsoft_DequantizeLinear;
    constant_3{{"constant_3<br>[], id=4, ty=4<br>/norm_k/Constant_output_0_QuantizeLinear_Output"}}
    class constant_3 constant;
    constant_4{{"constant_4<br>[], id=5, ty=1<br>/norm_k/Constant_output_0_scale"}}
    class constant_4 constant;
    constant_5{{"constant_5<br>[], id=6, ty=4<br>/norm_k/Constant_output_0_zero_point"}}
    class constant_5 constant;
    com_microsoft_DequantizeLinear_1["com_microsoft_DequantizeLinear_1<br>[], id=7, ty=1<br>/norm_k/Constant_output_0_DequantizeLinear_Output"]
    constant_3 -.-> com_microsoft_DequantizeLinear_1
    constant_4 -.-> com_microsoft_DequantizeLinear_1
    constant_5 -.-> com_microsoft_DequantizeLinear_1
    class com_microsoft_DequantizeLinear_1 com_microsoft_DequantizeLinear;
    input_0[\"input_0<br>[2000,64], id=8, ty=1<br>encoder.pos_emb.pe_k.weight_DequantizeLinear_Output"/]
    classDef input fill:#add8e6,stroke:#00008b,stroke-width:2px;;
    class input_0 input;
    constant_6{{"constant_6<br>[25,475], id=9, ty=7<br>/pos_emb/Constant_output_0"}}
    class constant_6 constant;
    Gather_0["Gather_0<br>[25,475,64], id=10, ty=1<br>/pos_emb/pe_k/Gather_output_0"]
    input_0 -.-> Gather_0
    constant_6 -.-> Gather_0
    constant_7{{"constant_7<br>[], id=11, ty=1<br>encoder.pos_emb.pe_k.weight_scale"}}
    class constant_7 constant;
    constant_8{{"constant_8<br>[], id=12, ty=4<br>encoder.pos_emb.pe_k.weight_zero_point"}}
    class constant_8 constant;
    com_microsoft_QuantizeLinear_0["com_microsoft_QuantizeLinear_0<br>[25,475,64], id=13, ty=4<br>/pos_emb/pe_k/Gather_output_0_QuantizeLinear_Output"]
    Gather_0 -.-> com_microsoft_QuantizeLinear_0
    constant_7 -.-> com_microsoft_QuantizeLinear_0
    constant_8 -.-> com_microsoft_QuantizeLinear_0
    classDef com_microsoft_QuantizeLinear fill:#f08080,stroke:#8b0000,stroke-width:2px;;
    class com_microsoft_QuantizeLinear_0 com_microsoft_QuantizeLinear;
    com_microsoft_DequantizeLinear_2["com_microsoft_DequantizeLinear_2<br>[25,475,64], id=14, ty=1<br>/pos_emb/pe_k/Gather_output_0_DequantizeLinear_Output"]
    com_microsoft_QuantizeLinear_0 -.-> com_microsoft_DequantizeLinear_2
    constant_7 -.-> com_microsoft_DequantizeLinear_2
    constant_8 -.-> com_microsoft_DequantizeLinear_2
    class com_microsoft_DequantizeLinear_2 com_microsoft_DequantizeLinear;
    constant_9{{"constant_9<br>[1], id=15, ty=7<br>7379"}}
    class constant_9 constant;
    ReduceMean_0["ReduceMean_0<br>[25,475,1], id=16, ty=1<br>/norm_k/ReduceMean_output_0"]
    com_microsoft_DequantizeLinear_2 -.-> ReduceMean_0
    constant_9 -.-> ReduceMean_0
    constant_10{{"constant_10<br>[], id=17, ty=1<br>/norm_k/ReduceMean_output_0_scale"}}
    class constant_10 constant;
    constant_11{{"constant_11<br>[], id=18, ty=4<br>/norm_k/ReduceMean_output_0_zero_point"}}
    class constant_11 constant;
    com_microsoft_QuantizeLinear_1["com_microsoft_QuantizeLinear_1<br>[25,475,1], id=19, ty=4<br>/norm_k/ReduceMean_output_0_QuantizeLinear_Output"]
    ReduceMean_0 -.-> com_microsoft_QuantizeLinear_1
    constant_10 -.-> com_microsoft_QuantizeLinear_1
    constant_11 -.-> com_microsoft_QuantizeLinear_1
    class com_microsoft_QuantizeLinear_1 com_microsoft_QuantizeLinear;
    com_microsoft_DequantizeLinear_3["com_microsoft_DequantizeLinear_3<br>[25,475,1], id=20, ty=1<br>/norm_k/ReduceMean_output_0_DequantizeLinear_Output"]
    com_microsoft_QuantizeLinear_1 -.-> com_microsoft_DequantizeLinear_3
    constant_10 -.-> com_microsoft_DequantizeLinear_3
    constant_11 -.-> com_microsoft_DequantizeLinear_3
    class com_microsoft_DequantizeLinear_3 com_microsoft_DequantizeLinear;
    com_microsoft_DequantizeLinear_4["com_microsoft_DequantizeLinear_4<br>[25,475,64], id=21, ty=1<br>/pos_emb/pe_k/Gather_output_0_DequantizeLinear_Output/duplicated"]
    com_microsoft_QuantizeLinear_0 -.-> com_microsoft_DequantizeLinear_4
    constant_7 -.-> com_microsoft_DequantizeLinear_4
    constant_8 -.-> com_microsoft_DequantizeLinear_4
    class com_microsoft_DequantizeLinear_4 com_microsoft_DequantizeLinear;
    Sub_0["Sub_0<br>[25,475,64], id=22, ty=1<br>/norm_k/Sub_output_0"]
    com_microsoft_DequantizeLinear_4 -.-> Sub_0
    com_microsoft_DequantizeLinear_3 -.-> Sub_0
    classDef Sub fill:#add8e6,stroke:#00008b,stroke-width:2px;;
    class Sub_0 Sub;
    constant_12{{"constant_12<br>[], id=23, ty=1<br>/norm_k/Sub_output_0_scale"}}
    class constant_12 constant;
    constant_13{{"constant_13<br>[], id=24, ty=4<br>/norm_k/Sub_output_0_zero_point"}}
    class constant_13 constant;
    com_microsoft_QuantizeLinear_2["com_microsoft_QuantizeLinear_2<br>[25,475,64], id=25, ty=4<br>/norm_k/Sub_output_0_QuantizeLinear_Output"]
    Sub_0 -.-> com_microsoft_QuantizeLinear_2
    constant_12 -.-> com_microsoft_QuantizeLinear_2
    constant_13 -.-> com_microsoft_QuantizeLinear_2
    class com_microsoft_QuantizeLinear_2 com_microsoft_QuantizeLinear;
    com_microsoft_DequantizeLinear_5["com_microsoft_DequantizeLinear_5<br>[25,475,64], id=26, ty=1<br>/norm_k/Sub_output_0_DequantizeLinear_Output"]
    com_microsoft_QuantizeLinear_2 -.-> com_microsoft_DequantizeLinear_5
    constant_12 -.-> com_microsoft_DequantizeLinear_5
    constant_13 -.-> com_microsoft_DequantizeLinear_5
    class com_microsoft_DequantizeLinear_5 com_microsoft_DequantizeLinear;
    Pow_0["Pow_0<br>[25,475,64], id=27, ty=1<br>/norm_k/Pow_output_0"]
    com_microsoft_DequantizeLinear_5 -.-> Pow_0
    com_microsoft_DequantizeLinear_1 -.-> Pow_0
    constant_14{{"constant_14<br>[], id=28, ty=1<br>/norm_k/Pow_output_0_scale"}}
    class constant_14 constant;
    constant_15{{"constant_15<br>[], id=29, ty=4<br>/norm_k/Pow_output_0_zero_point"}}
    class constant_15 constant;
    com_microsoft_QuantizeLinear_3["com_microsoft_QuantizeLinear_3<br>[25,475,64], id=30, ty=4<br>/norm_k/Pow_output_0_QuantizeLinear_Output"]
    Pow_0 -.-> com_microsoft_QuantizeLinear_3
    constant_14 -.-> com_microsoft_QuantizeLinear_3
    constant_15 -.-> com_microsoft_QuantizeLinear_3
    class com_microsoft_QuantizeLinear_3 com_microsoft_QuantizeLinear;
    com_microsoft_DequantizeLinear_6["com_microsoft_DequantizeLinear_6<br>[25,475,64], id=31, ty=1<br>/norm_k/Pow_output_0_DequantizeLinear_Output"]
    com_microsoft_QuantizeLinear_3 -.-> com_microsoft_DequantizeLinear_6
    constant_14 -.-> com_microsoft_DequantizeLinear_6
    constant_15 -.-> com_microsoft_DequantizeLinear_6
    class com_microsoft_DequantizeLinear_6 com_microsoft_DequantizeLinear;
    ReduceMean_1["ReduceMean_1<br>[25,475,1], id=32, ty=1<br>/norm_k/ReduceMean_1_output_0"]
    com_microsoft_DequantizeLinear_6 -.-> ReduceMean_1
    constant_9 -.-> ReduceMean_1
    constant_16{{"constant_16<br>[], id=33, ty=1<br>/norm_k/ReduceMean_1_output_0_scale"}}
    class constant_16 constant;
    constant_17{{"constant_17<br>[], id=34, ty=4<br>/norm_k/ReduceMean_1_output_0_zero_point"}}
    class constant_17 constant;
    com_microsoft_QuantizeLinear_4["com_microsoft_QuantizeLinear_4<br>[25,475,1], id=35, ty=4<br>/norm_k/ReduceMean_1_output_0_QuantizeLinear_Output"]
    ReduceMean_1 -.-> com_microsoft_QuantizeLinear_4
    constant_16 -.-> com_microsoft_QuantizeLinear_4
    constant_17 -.-> com_microsoft_QuantizeLinear_4
    class com_microsoft_QuantizeLinear_4 com_microsoft_QuantizeLinear;
    com_microsoft_DequantizeLinear_7["com_microsoft_DequantizeLinear_7<br>[25,475,1], id=36, ty=1<br>/norm_k/ReduceMean_1_output_0_DequantizeLinear_Output"]
    com_microsoft_QuantizeLinear_4 -.-> com_microsoft_DequantizeLinear_7
    constant_16 -.-> com_microsoft_DequantizeLinear_7
    constant_17 -.-> com_microsoft_DequantizeLinear_7
    class com_microsoft_DequantizeLinear_7 com_microsoft_DequantizeLinear;
    Add_0["Add_0<br>[25,475,1], id=37, ty=1<br>/norm_k/Add_output_0"]
    com_microsoft_DequantizeLinear_7 -.-> Add_0
    com_microsoft_DequantizeLinear_0 -.-> Add_0
    classDef Add fill:#f5f5dc,stroke:#8b4513,stroke-width:2px;;
    class Add_0 Add;
    constant_18{{"constant_18<br>[], id=38, ty=1<br>/norm_k/Add_output_0_scale"}}
    class constant_18 constant;
    constant_19{{"constant_19<br>[], id=39, ty=4<br>/norm_k/Add_output_0_zero_point"}}
    class constant_19 constant;
    com_microsoft_QuantizeLinear_5["com_microsoft_QuantizeLinear_5<br>[25,475,1], id=40, ty=4<br>/norm_k/Add_output_0_QuantizeLinear_Output"]
    Add_0 -.-> com_microsoft_QuantizeLinear_5
    constant_18 -.-> com_microsoft_QuantizeLinear_5
    constant_19 -.-> com_microsoft_QuantizeLinear_5
    class com_microsoft_QuantizeLinear_5 com_microsoft_QuantizeLinear;
    com_microsoft_DequantizeLinear_8["com_microsoft_DequantizeLinear_8<br>[25,475,1], id=41, ty=1<br>/norm_k/Add_output_0_DequantizeLinear_Output"]
    com_microsoft_QuantizeLinear_5 -.-> com_microsoft_DequantizeLinear_8
    constant_18 -.-> com_microsoft_DequantizeLinear_8
    constant_19 -.-> com_microsoft_DequantizeLinear_8
    class com_microsoft_DequantizeLinear_8 com_microsoft_DequantizeLinear;
    Sqrt_0["Sqrt_0<br>[25,475,1], id=42, ty=1<br>/norm_k/Sqrt_output_0"]
    com_microsoft_DequantizeLinear_8 -.-> Sqrt_0
    constant_20{{"constant_20<br>[], id=43, ty=1<br>/norm_k/Sqrt_output_0_scale"}}
    class constant_20 constant;
    constant_21{{"constant_21<br>[], id=44, ty=4<br>/norm_k/Sqrt_output_0_zero_point"}}
    class constant_21 constant;
    com_microsoft_QuantizeLinear_6["com_microsoft_QuantizeLinear_6<br>[25,475,1], id=45, ty=4<br>/norm_k/Sqrt_output_0_QuantizeLinear_Output"]
    Sqrt_0 -.-> com_microsoft_QuantizeLinear_6
    constant_20 -.-> com_microsoft_QuantizeLinear_6
    constant_21 -.-> com_microsoft_QuantizeLinear_6
    class com_microsoft_QuantizeLinear_6 com_microsoft_QuantizeLinear;
    com_microsoft_DequantizeLinear_9["com_microsoft_DequantizeLinear_9<br>[25,475,1], id=46, ty=1<br>/norm_k/Sqrt_output_0_DequantizeLinear_Output"]
    com_microsoft_QuantizeLinear_6 -.-> com_microsoft_DequantizeLinear_9
    constant_20 -.-> com_microsoft_DequantizeLinear_9
    constant_21 -.-> com_microsoft_DequantizeLinear_9
    class com_microsoft_DequantizeLinear_9 com_microsoft_DequantizeLinear;
    com_microsoft_DequantizeLinear_10["com_microsoft_DequantizeLinear_10<br>[25,475,64], id=47, ty=1<br>/norm_k/Sub_output_0_DequantizeLinear_Output/duplicated"]
    com_microsoft_QuantizeLinear_2 -.-> com_microsoft_DequantizeLinear_10
    constant_12 -.-> com_microsoft_DequantizeLinear_10
    constant_13 -.-> com_microsoft_DequantizeLinear_10
    class com_microsoft_DequantizeLinear_10 com_microsoft_DequantizeLinear;
    Div_0["Div_0<br>[25,475,64], id=48, ty=1<br>/norm_k/Div_output_0"]
    com_microsoft_DequantizeLinear_10 -.-> Div_0
    com_microsoft_DequantizeLinear_9 -.-> Div_0
    constant_22{{"constant_22<br>[], id=49, ty=1<br>/norm_k/Div_output_0_scale"}}
    class constant_22 constant;
    constant_23{{"constant_23<br>[], id=50, ty=4<br>/norm_k/Div_output_0_zero_point"}}
    class constant_23 constant;
    com_microsoft_QuantizeLinear_7["com_microsoft_QuantizeLinear_7<br>[25,475,64], id=51, ty=4<br>/norm_k/Div_output_0_QuantizeLinear_Output"]
    Div_0 -.-> com_microsoft_QuantizeLinear_7
    constant_22 -.-> com_microsoft_QuantizeLinear_7
    constant_23 -.-> com_microsoft_QuantizeLinear_7
    class com_microsoft_QuantizeLinear_7 com_microsoft_QuantizeLinear;
    com_microsoft_DequantizeLinear_11["com_microsoft_DequantizeLinear_11<br>[25,475,64], id=52, ty=1<br>/norm_k/Div_output_0_DequantizeLinear_Output"]
    com_microsoft_QuantizeLinear_7 -.-> com_microsoft_DequantizeLinear_11
    constant_22 -.-> com_microsoft_DequantizeLinear_11
    constant_23 -.-> com_microsoft_DequantizeLinear_11
    class com_microsoft_DequantizeLinear_11 com_microsoft_DequantizeLinear;
    Transpose_0["Transpose_0<br>[25,64,475], id=53, ty=1<br>/Transpose_6_output_0"]
    com_microsoft_DequantizeLinear_11 -.-> Transpose_0
    classDef Transpose fill:#ffdab9,stroke:#8b4513,stroke-width:2px;;
    class Transpose_0 Transpose;
    com_microsoft_QuantizeLinear_8[["com_microsoft_QuantizeLinear_8<br>[25,64,475], id=54, ty=4<br>/Transpose_6_output_0_QuantizeLinear_Output"]]
    Transpose_0 --o com_microsoft_QuantizeLinear_8
    constant_22 --o com_microsoft_QuantizeLinear_8
    constant_23 --o com_microsoft_QuantizeLinear_8
    class com_microsoft_QuantizeLinear_8 com_microsoft_QuantizeLinear;
