<!--
    Copyright (C) 2023 – 2024 Advanced Micro Devices, Inc. All rights reserved.
    Licensed under the MIT License.
 -->
flowchart TB
    input_0[\"input_0<br>[1,64,56,56], id=0, ty=3<br>138"/]
    classDef input fill:#add8e6,stroke:#00008b,stroke-width:2px;;
    class input_0 input;
    DequantizeLinear_0["DequantizeLinear_0<br>[1,64,56,56], id=3, ty=1<br>141"]
    input_0 -.-> DequantizeLinear_0
    classDef DequantizeLinear fill:#fafad2,stroke:#b8860b,stroke-width:2px;;
    class DequantizeLinear_0 DequantizeLinear;
    QuantizeLinear_0["QuantizeLinear_0<br>[64,64,1,1], id=7, ty=3<br>144"]
    classDef QuantizeLinear fill:#ffa07a,stroke:#8b0000,stroke-width:2px;;
    class QuantizeLinear_0 QuantizeLinear;
    DequantizeLinear_1["DequantizeLinear_1<br>[64,64,1,1], id=10, ty=1<br>147"]
    QuantizeLinear_0 -.-> DequantizeLinear_1
    class DequantizeLinear_1 DequantizeLinear;
    QuantizeLinear_1["QuantizeLinear_1<br>[64], id=14, ty=3<br>150"]
    class QuantizeLinear_1 QuantizeLinear;
    DequantizeLinear_2["DequantizeLinear_2<br>[64], id=17, ty=1<br>153"]
    QuantizeLinear_1 -.-> DequantizeLinear_2
    class DequantizeLinear_2 DequantizeLinear;
    Conv_0["Conv_0<br>[1,64,56,56], id=18, ty=1<br>154"]
    DequantizeLinear_0 -.-> Conv_0
    DequantizeLinear_1 -.-> Conv_0
    DequantizeLinear_2 -.-> Conv_0
    classDef Conv fill:#f08080,stroke:#8b0000,stroke-width:2px;;
    class Conv_0 Conv;
    Relu_0["Relu_0<br>[1,64,56,56], id=19, ty=1<br>155"]
    Conv_0 -.-> Relu_0
    classDef Relu fill:#ffb6c1,stroke:#8b0000,stroke-width:2px;;
    class Relu_0 Relu;
    QuantizeLinear_2[["QuantizeLinear_2<br>[1,64,56,56], id=22, ty=3<br>158"]]
    Relu_0 --o QuantizeLinear_2
    class QuantizeLinear_2 QuantizeLinear;
    QuantizeLinear_3["QuantizeLinear_3<br>[256,64,1,1], id=26, ty=3<br>203"]
    class QuantizeLinear_3 QuantizeLinear;
    DequantizeLinear_3["DequantizeLinear_3<br>[256,64,1,1], id=29, ty=1<br>206"]
    QuantizeLinear_3 -.-> DequantizeLinear_3
    class DequantizeLinear_3 DequantizeLinear;
    QuantizeLinear_4["QuantizeLinear_4<br>[256], id=33, ty=3<br>209"]
    class QuantizeLinear_4 QuantizeLinear;
    DequantizeLinear_4["DequantizeLinear_4<br>[256], id=36, ty=1<br>212"]
    QuantizeLinear_4 -.-> DequantizeLinear_4
    class DequantizeLinear_4 DequantizeLinear;
    Conv_1["Conv_1<br>[1,256,56,56], id=37, ty=1<br>213"]
    DequantizeLinear_0 -.-> Conv_1
    DequantizeLinear_3 -.-> Conv_1
    DequantizeLinear_4 -.-> Conv_1
    class Conv_1 Conv;
    QuantizeLinear_5[["QuantizeLinear_5<br>[1,256,56,56], id=40, ty=3<br>216"]]
    Conv_1 --o QuantizeLinear_5
    class QuantizeLinear_5 QuantizeLinear;
