name: Notify Teams
description: Sends a notification to Microsoft Teams with build status.

inputs:
  overall-status:
    description: 'Overall status of the build (success or failure)'
    required: true
  run-url:
    description: 'URL to the GitHub Actions run'
    required: true
  action-name:
    description: 'Name of the job or action'
    required: true
  workflow-status:
    description: 'Status of the workflow'
    required: true

runs:
  using: "composite"
  steps:
    - name: Send Notification
      shell: bash
      run: |
        WEBHOOK_URL="https://amdcloud.webhook.office.com/webhookb2/133d4f16-689b-4281-a94b-44725b948c77@3dd8961f-e488-4e60-8e11-a82d994e183d/IncomingWebhook/4dad5927e4bf444fa82e7c6c59307bee/f9e22351-f1c9-494f-88c5-8e04accf2ffe"

        if [[ "${{ inputs.overall-status }}" == "failure" ]]; then
          curl -H 'Content-Type: application/json' \
               -d '{
                    "type": "message",
                    "attachments": [
                      {
                        "contentType": "application/vnd.microsoft.card.adaptive",
                        "content": {
                          "type": "AdaptiveCard",
                          "version": "1.2",
                          "body": [
                            {
                              "type": "TextBlock",
                              "size": "Large",
                              "weight": "Bolder",
                              "text": "<at>jennyang</at>"
                            },
                            {
                              "type": "TextBlock",
                              "text": "**Job Name:** '"${{ inputs.action-name }}"'",
                              "color": "Attention"
                            },
                            {
                              "type": "TextBlock",
                              "text": "**Workflow Status:** '"${{ inputs.workflow-status }}"'",
                              "color": "Attention"
                            },
                            {
                              "type": "TextBlock",
                              "text": "The build and test failed. Please check the logs.",
                              "color": "Attention"
                            }
                          ],
                          "msteams": {
                            "width": "Full",
                            "entities": [
                              {
                                "type": "mention",
                                "text": "<at>jennyang</at>",
                                "mentioned": {
                                  "id": "jennyang@amd.com",
                                  "name": "Yang, Jennifer"
                                }
                              }
                            ]
                          },
                          "actions": [
                            {
                              "type": "Action.OpenUrl",
                              "title": "View Run",
                              "url": "'"${{ inputs.run-url }}"'"
                            }
                          ]
                        }
                      }
                    ]
                  }' \
               "$WEBHOOK_URL"
        else
          curl -H 'Content-Type: application/json' \
               -d '{
                    "type": "message",
                    "attachments": [
                      {
                        "contentType": "application/vnd.microsoft.card.adaptive",
                        "content": {
                          "type": "AdaptiveCard",
                          "version": "1.2",
                          "body": [
                            {
                              "type": "TextBlock",
                              "text": "**Job Name:** '"${{ inputs.action-name }}"'",
                              "color": "Good"  
                            },
                            {
                              "type": "TextBlock",
                              "text": "**Workflow Status:** '"${{ inputs.workflow-status }}"'",
                              "color": "Good" 
                            },
                            {
                              "type": "TextBlock",
                              "text": "The build and test completed successfully.",
                              "color": "Good"  
                            }
                          ],
                          "msteams": {
                            "width": "Full"
                          },
                          "actions": [
                            {
                              "type": "Action.OpenUrl",
                              "title": "View Run",
                              "url": "'"${{ inputs.run-url }}"'"
                            }
                          ]
                        }
                      }
                    ]
                  }' \
               "$WEBHOOK_URL"
        fi
