{
    "Reshape1_allowzero": 0,
    "Transpose4_perm": [2, 0, 1, 3],
    "Reshape7_allowzero": 0,
    "Transpose10_perm": [0, 2, 1, 3],
    "Reshape13_allowzero": 0,
    "Gather16_axis": 0,
    "Reshape19_allowzero": 0,
    "Transpose26_perm": [0, 1, 3, 2],
    "Gather30_axis": 0,
    "Reshape33_allowzero": 0,
    "Softmax39_axis": -1,
    "Gather43_axis": 0,
    "Reshape46_allowzero": 0,
    "Transpose49_perm": [0, 1, 3, 2],
    "Transpose55_perm": [0, 3, 1, 2],
    "Reshape58_allowzero": 0,
    "design_param": "4x2",
    "QKT_input_qparams": [
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Mul_2_output_0_scale",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Mul_2_output_0_zero_point",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/qkv/Add_output_0_scale",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/qkv/Add_output_0_zero_point",
    ],
    "QKT_output_qparams": [
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/MatMul_output_0_scale",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/MatMul_output_0_zero_point",
    ],
    "VSQKT_input_qparams": [
        "/blocks.3/blocks.3.0/channel_block/channel_attn/fn/Softmax_output_0_scale",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Softmax_output_0_zero_point",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/qkv/Add_output_0_scale",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/qkv/Add_output_0_zero_point",
    ],
    "VSQKT_output_qparams": [
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/MatMul_1_output_0_scale",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/MatMul_1_output_0_zero_point",
    ],
    "softmax_input_qparams": [
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/MatMul_output_0_scale",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/MatMul_output_0_zero_point",
    ],
    "softmax_output_qparams": [
        "/blocks.3/blocks.3.0/channel_block/channel_attn/fn/Softmax_output_0_scale",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Softmax_output_0_zero_point",
    ],
    "MUL_input_qparams": [
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/qkv/Add_output_0_scale",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/qkv/Add_output_0_zero_point",
    ],
    "MUL_weight_qparams": [
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Pow_output_0_quantized",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Pow_output_0_scale",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Pow_output_0_zero_point",
    ],
    "MUL_output_qparams": [
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Mul_2_output_0_scale",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Mul_2_output_0_zero_point",
    ],
    "QKT_K_dim": 3136,
    "VSQKT_K_dim": 32,
    "nodes": [
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/qkv/Add_output_0_DequantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Reshape_output_0",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Reshape_output_0_QuantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Reshape_output_0_DequantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Transpose_output_0",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Transpose_output_0_QuantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Transpose_output_0_DequantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Reshape_1_output_0",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Reshape_1_output_0_QuantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Reshape_1_output_0_DequantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Transpose_1_output_0",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Transpose_1_output_0_QuantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Transpose_1_output_0_DequantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Reshape_2_output_0",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Reshape_2_output_0_QuantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Reshape_2_output_0_DequantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Gather_3_output_0",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Gather_3_output_0_QuantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Gather_3_output_0_DequantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Reshape_3_output_0",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Reshape_3_output_0_QuantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Reshape_3_output_0_DequantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Pow_output_0_DequantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Mul_2_output_0",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Mul_2_output_0_QuantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Mul_2_output_0_DequantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Transpose_2_output_0",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Transpose_2_output_0_QuantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Transpose_2_output_0_DequantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Reshape_2_output_0_DequantizeLinear_Output/duplicated",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Gather_4_output_0",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Gather_4_output_0_QuantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Gather_4_output_0_DequantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Reshape_4_output_0",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Reshape_4_output_0_QuantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Reshape_4_output_0_DequantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/MatMul_output_0",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/MatMul_output_0_QuantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/MatMul_output_0_DequantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Softmax_output_0",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Softmax_output_0_QuantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Softmax_output_0_DequantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Reshape_2_output_0_DequantizeLinear_Output/duplicated_token_22",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Gather_5_output_0",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Gather_5_output_0_QuantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Gather_5_output_0_DequantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Reshape_5_output_0",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Reshape_5_output_0_QuantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Reshape_5_output_0_DequantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Transpose_3_output_0",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Transpose_3_output_0_QuantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Transpose_3_output_0_DequantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/MatMul_1_output_0",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/MatMul_1_output_0_QuantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/MatMul_1_output_0_DequantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Transpose_4_output_0",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Transpose_4_output_0_QuantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Transpose_4_output_0_DequantizeLinear_Output",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Reshape_6_output_0",
        "/blocks.0/blocks.0.0/channel_block/channel_attn/fn/Reshape_6_output_0_QuantizeLinear_Output",
    ],
    "orig_output_shape": [1, 3136, 128],
}
